language: node_js
addons:
  sauce_connect: true
env:
  global:
  - secure: Qm+pjXR3CE9xUqYOnQv9sQvA6LLRS32a2LxwxRMv8HWJ0RRFkKik4jnLIcH0lKl0t8qlyYSG1THs5gLHdjkO+9pf/XvAQ4b6Pnw/oUSjM5jOiP4J4AH2NQApwSyF8D6kGfghYNnkHug9lUoOMTCNrBIsfjAZ5HGQXwPm0mxT9+htYlvGyc14MsDYVEwgHy8/JoNdAnQHIpfNX44gpXvIwESk4yL6H02XzzsI4gcjrDgdHwTV10K6gqVT3qtOBrEbpyuGeJ+vf8vfxTYlwKUn9iNACdd4ZJFKyOa0p/7F5NBZkpJnSsNqB7A6/bsEG1k2RTv9Yyu9fC6LUnOgGltC1cuceNKI/yvlmSaavF2mXicL5wL2/yb5pJdFuO06mDm1oHLf4ZYhwM7XR0tSX0KD715i8hU78pSUcOaMrYylQjBOm6UxiaKI48bk83rimq8uzEzpK+zLfgRETKrnnGwcPY4xvE0IfEBG9CllkbFRjhmf+lPwMSOhh4N7jG+pMI/gmA5RXns+/Uv2AN81mP92bl+yMGlPXLMS9RQ028K1x4vAa1SQi8rsPvGSzPgorGyIgl9FvyTdqqnQrxuCpZTkavnj9npOBopeutPvys9tJ8/ewzuPwnSg7moJJSFYtUVxPWvIvjwpsdN0nJkGj6u7dqv83jUPwW7iUIyk8Q8H68Y=
  - secure: HW7/uPQ6jLyEDQrLjS8IXDhJ7DUYwozlTIJE4KjdeGqY3d1vfOFXGsPwIqbbAykpEsturbumkZeE6pAIOcXY7xNJenRPkJxCLn+VjZJeOkg8+qcfAsDRVIA/RKIXpHyHYJ9WGuY4LEVpn5Z9lJyl2Gpnz7Ut7zBPK0ymfw18t5uJksRXq6dEj1roI+a3Z+NQKjdUx5jXQ2WsexJ+4Y8jjgeFasF12VcEmc9NnBvD5dxdv+JsL5vF5Uyx77zgj+iBVAEwQuPcs65BEmWQOs+icOTc1b7xgMawBppWbJ8Qbz84Z23+najJmc0yUdbgej6NQzUgVD48N82yJ58GM9piShGisJauimBRYO51TRBRsbLJMVXKzPW06oK5PUYqn79Q7sh0ArUfBxESS1Yc7YutP5G/2hYRnwqG5ImtF9k+UHlwN/Rsxuki8dSdI88nrtnSjSpgbHws55Mb1tpwSEhrRer7BIv4uXh46JzWafmqAkpCUPJMrZ891dvn76Pm2r9w0I7s+0Jahc9LRpcnkH+Lw6MF0G+OvWdqhjhYr58J4x/QoCHGP+RjDyk6g5Vqf41wgHS5qPehLWk5yl0FJ6Jcwxvw9yY+vkVSQoC7hh3DOBeIW1Z84nfAEkjZnUO6YQMKovR/2SWUOQI9/XVBwZq+FJEewgddBcDxofwrlOhS7Kk=
before_script:
- python -m SimpleHTTPServer &
- sleep 2
node_js:
- '0.12'
